Repository wecode-bootcamp-korea/24-2nd-METABOX-frontend, pull requests merged in 2021-09, with the labels that each got.

#1 [24기 이송현] Modify: 빠른 예매 달력 리뷰 요청
  package-lock.json
  package.json
  src/Routes.js
  src/pages/Booking/Booking.jsx
  src/pages/Booking/components/Calendar/Calendar.jsx
  src/pages/Booking/components/Hour/Hour.jsx
  src/pages/Booking/components/Movie/Movie.jsx
  src/pages/Booking/components/Theater/Theater.jsx
Labels: Status: 수정 요청

#6 [24기 김동준] ADD:[feature/detail] 상세페이지 영화 정보 컴포넌트 구현 완료(chart.js)
  package.json
  src/pages/Details/Details.jsx
  src/pages/Details/components/MovieDataInfo/AverageScore.jsx
  src/pages/Details/components/MovieDataInfo/MovieDataInfo.jsx
  src/pages/Details/components/MovieDataInfo/NumberOfAudienceByDate.jsx
  src/pages/Details/components/MovieDataInfo/PointRating.jsx
  src/pages/Details/components/MovieDataInfo/TicketingRate.jsx
  src/styles/GlobalStyles.jsx
Labels: Status: 리뷰 요청, Status: 추가 기능 구현중

#2 [24기 김영현] [Feature/modal] Add: 카카오 소셜 로그인 구현 및 컴포넌트 이동
  .gitignore
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  src/components/Modal/Form.jsx
  src/components/Modal/Form/Form.jsx
  src/components/Modal/GuideText.jsx
  src/components/Modal/Inputs.jsx
  src/components/Modal/KakaoLogin.jsx
  src/components/Modal/Modal.jsx
  src/components/Nav/Nav.jsx
  src/config.js
  src/pages/Main/Main.jsx
Labels: Status: Accepted

#3 [24기 김동준] [feature/navigation] Add: Navigation Bar 레이아웃 및 버튼 클릭 이벤트 추가
  public/image/full_logo_color.png
  public/image/full_logo_white.png
  public/image/logo_bg_color.png
  public/image/logo_bg_white.png
  public/image/logo_m_initial.png
  src/Routes.js
  src/components/Modal/Modal.jsx
  src/components/Nav/Nav.jsx
  src/components/Nav/NavButton.jsx
  src/components/Nav/SearchBar.jsx
  src/components/Nav/SiteMap.jsx
  src/config.js
  src/styles/GlobalStyles.jsx
Labels: Status: 리뷰 요청

#8 [24기 김동준] [feature/main] 메인 레이아웃, 더보기, 정렬
  src/pages/Main/AddMovieButton.jsx
  src/pages/Main/Main.jsx
  src/pages/Main/Movie.jsx
  src/pages/Main/SortingSearchArea.jsx
  src/styles/GlobalStyles.jsx
Labels: Status: 리뷰 요청

#7 [24기 김영현] [Feature/write] Add: config 사용 및 리팩토링 | Wip: 무비포스트 작성 서버 통신
  public/data/harry.json
  src/Routes.js
  src/config.js
  src/pages/MoviePostWrite/MoviePostWrite.jsx
  src/pages/MoviePostWrite/Postcontent.jsx
  src/pages/MoviePostWrite/WriteFirstStep.jsx
  src/pages/MoviePostWrite/WriteSecondStep.jsx
Labels: Status: 리뷰 요청, Status: 추가 기능 구현중

#5 [24기 김영현] [Feature/moviepost] Add: Footer 제작 및 리팩토링, 페이지네이션 제작 | Wip: 서버 통신
  package-lock.json
  public/data/harry.json
  public/data/page.json
  public/image/cat.jpeg
  src/Routes.js
  src/components/Footer/Footer.jsx
  src/components/Modal/Inputs.jsx
  src/components/Modal/KakaoLogin.jsx
  src/components/Modal/Modal.jsx
  src/components/Nav/Nav.jsx
  src/components/Nav/SearchBar.jsx
  src/components/Nav/SiteMap.jsx
  src/config.js
  src/image/WallPaper.jpeg
  src/image/curtain.jpeg
  src/image/harrypoter.jpg
  src/image/sdf.jpeg
  src/image/wp2619141.jpeg
  src/pages/Main/Main.jsx
  src/pages/MoviePost/AllRankMovies.jsx
  src/pages/MoviePost/MoviePost.jsx
  src/pages/MoviePost/PostMap.jsx
  src/pages/MoviePost/PostModal.jsx
  src/pages/MoviePost/Posts.jsx
  src/utils/api.js
Labels: Status: 리뷰 요청, Status: 추가 기능 구현중

#4 [24기 이송현]Modify: 빠른 예매 달력 레이아웃 및 기능 구현 완료 리뷰 요청
  package-lock.json
  package.json
  public/data/README.md
  public/data/movieCity.json
  public/data/movieData.json
  public/data/movieLocation.json
  pull_request_template.md
  src/components/Nav/Nav.jsx
  src/components/Nav/SearchBar.jsx
  src/config.js
  src/pages/Booking/Booking.jsx
  src/pages/Booking/components/Calendar/Calendar.jsx
  src/pages/Booking/components/Calendar/TwoWeeksCalendar.jsx
  src/pages/Booking/components/Calendar/hooks/useCalendar.jsx
  src/pages/Booking/components/Calendar/utils.js
  src/pages/Booking/components/CalendarDatePicker/CalendarDatePicker.jsx
  src/pages/Booking/components/Hour/Hour.jsx
  src/pages/Booking/components/Movie/Movie.jsx
  src/pages/Booking/components/Movie/MovieList.jsx
  src/pages/Booking/components/Movie/hooks/useMovieData.jsx
  src/pages/Booking/components/Theater/ThaterList.jsx
  src/pages/Booking/components/Theater/Theater.jsx
  src/pages/Booking/components/Time/Time.jsx
  src/pages/Booking/components/Time/TimeList.jsx
  src/pages/Booking/components/Time/TimePartList.jsx
  src/pages/Booking/components/Time/utils.js
Labels: Status: 리뷰 요청, Status: 추가 기능 구현중

#9 [24기 이송현]Modify: 빠른 예매 상영시간표 로직 구현
  public/data/movieLocation.json
  src/config.js
  src/pages/Booking/components/Theater/ThaterList.jsx
  src/pages/Booking/components/Time/Time.jsx
Labels: Status: 리뷰 요청, Status: 수정 요청
